# Use Python slim image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy requirements.txt first to cache dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy app files
COPY . /app

# Expose the port (if needed)
EXPOSE 80

# Command to run the bot
CMD ["python", "main.py"]
